### PR TITLE
add section on Actions

### PR DESCRIPTION
**Pull request by driftregion**

### CODE REVIEW

**Review by gavanderhoorn — CHANGES_REQUESTED** [review]
Thanks for the PR, this is a nice addition and clarification.

One request: could I ask you to please start each new sentence on a separate line? I realise the document doesn't do that right now, but it's a good habit in markdown documents as it makes diffs much easier to read (you get per-sentence diffs, instead of a single (very) large line which has changes *somewhere* embedded in that line).

**Comment by driftregion** [comment]
Got it, thanks for this tip!

**Review by gavanderhoorn — APPROVED** [review]
Thanks for the addition, and thanks for changing it to one-sentence-per-line.

**Comment by gavanderhoorn** [comment]
One thing I just noticed: the `GIT_AUTHOR_EMAIL` does not appear to be associated with your GH account. Would you want to fix that first?

**Comment by driftregion** [comment]
> One thing I just noticed: the `GIT_AUTHOR_EMAIL` does not appear to be associated with your GH account. Would you want to fix that first?

Done, thanks!

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Thanks for the contribution @driftregion.

**Pull request merged**
