### PR TITLE
Update license information of open62541

### PR DESCRIPTION
**Pull request by traversaro**
The project has been relicensed in https://github.com/open62541/open62541/commit/e5865742fc607627ae2b0a5077a7f2da58a7f269

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks.

It's MPL v2 even. If you could add that I'll merge.

**Comment by traversaro** [comment]
@gavanderhoorn updated.

**Comment by gavanderhoorn** [comment]
Thanks! Much appreciated :+1:

**Comment by traversaro** [comment]
Thanks for writing and sharing in public this interesting document in the first place!

**Comment by gavanderhoorn** [comment]
We'd have to thank @ipa-mirb for that :)

But good to hear that the document was valuable.

**Comment by ipa-mirb** [comment]
Thanks for the update Silvio, and thanks Gijs for the merge! Btw, if you are interested in ROS support for PLCs and industrial fieldbuses, keep an eye on this [event](https://rosindustrial.org/events/2018/5/23/ros-industrial-workshops-hrim-rosin-quality-hub-ftp-info-session), where we will have a session on it.

**Comment by traversaro** [comment]
Thanks @ipa-mirb for the interesting reference.

**Pull request merged**
